// Optional, consent-bound first-party events. Never serialize forms/URLs/PII.
const panel=document.querySelector('[data-analytics-consent]'),manage=document.querySelector('[data-analytics-manage]');
const root=document.documentElement;
let policy=null,granted=false,queue=[],timer=null,sending=false;
const en=(root.dataset.uiLocale??root.lang)!=='ru';
const privacySignal=()=>navigator.globalPrivacyControl===true||navigator.doNotTrack==='1';
const device=()=>matchMedia('(max-width:699px)').matches?'mobile':matchMedia('(max-width:1199px)').matches?'tablet':'desktop';
const source=()=>{if(!document.referrer)return'direct';try{const host=new URL(document.referrer).hostname;if(host===location.hostname)return'internal';if(/(^|\.)(google|bing|yandex|duckduckgo)\./i.test(host))return'search';if(/(^|\.)(t\.me|facebook\.com|instagram\.com|youtube\.com)$/i.test(host))return'social';}catch{}return'other';};
function recordEvent(name,extra={}){if(!granted||privacySignal()||!policy?.enabled)return;const locale=['ru','en','de','fr','es','ar','hi','ja','ko','zh-Hans'].includes(root.lang)?root.lang:undefined;queue.push({event_key:crypto.randomUUID(),event_name:name,...(root.dataset.contentId?{content_id:root.dataset.contentId}:{}),...(root.dataset.serviceId?{service_id:root.dataset.serviceId}:{}),...(locale?{locale}:{}),device:device(),source:source(),...extra});if(queue.length>=20)void flush();else if(timer===null)timer=setTimeout(()=>void flush(),1000);}
async function flush(){clearTimeout(timer);timer=null;if(sending||!granted||!queue.length)return;const batch=queue.splice(0,20);sending=true;try{const r=await fetch('/api/analytics/events',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:batch}),keepalive:true,signal:AbortSignal.timeout(5000)});if(!r.ok){granted=false;queue=[];}}catch{queue=[];}finally{sending=false;}}
async function choose(allowed){if(!policy)return;panel.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch('/api/analytics/consent',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({granted:allowed,policy_revision:policy.policy_revision}),signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error();const result=await r.json();granted=result.granted===true;queue=[];panel.hidden=true;try{localStorage.setItem('safr:analytics-decision:v1',JSON.stringify({revision:policy.policy_revision,granted}));}catch{}if(granted)recordEvent('page_view');}catch{panel.querySelector('[data-analytics-status]').textContent=en?'Could not save. Analytics remains off.':'Не удалось сохранить. Аналитика остаётся выключенной.';granted=false;}finally{panel.querySelectorAll('button').forEach(b=>b.disabled=false);}}
panel?.querySelector('[data-analytics-accept]')?.addEventListener('click',()=>void choose(true));
panel?.querySelector('[data-analytics-decline]')?.addEventListener('click',()=>void choose(false));
manage?.addEventListener('click',()=>{panel.hidden=false;panel.querySelector('button')?.focus();});
document.addEventListener('click',e=>{if(!(e.target instanceof Element))return;if(e.target.closest('[data-support-open]'))recordEvent('cta_click');if(e.target.closest('[data-language-choice]'))recordEvent('language_select');if(e.target.closest('a[href^="https://t.me/"]'))recordEvent('channel_click',{channel:'telegram'});});
document.addEventListener('safr:country-select',e=>{if(/^[A-Z]{2}$/.test(e.detail?.country??''))recordEvent('country_select',{country:e.detail.country});});
document.addEventListener('safr:country-selected',e=>{if(/^[A-Z]{2}$/.test(e.detail?.country??''))recordEvent('country_select',{country:e.detail.country});});
let formStarted=false;document.addEventListener('focusin',e=>{if(!formStarted&&e.target instanceof Element&&e.target.closest('[data-support-form]')){formStarted=true;recordEvent('form_start');}});
document.addEventListener('safr:lead-submitted',()=>recordEvent('form_submit'));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')void flush();});
async function init(){if(!panel||privacySignal())return;try{const r=await fetch('/api/analytics/policy',{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok)return;policy=await r.json();if(!policy.enabled||policy.blocked_by_privacy_signal)return;manage.hidden=false;let saved=null;try{saved=JSON.parse(localStorage.getItem('safr:analytics-decision:v1'));}catch{}granted=policy.has_consent===true;if(granted)recordEvent('page_view');else if(!saved||saved.revision!==policy.policy_revision||saved.granted)panel.hidden=false;}catch{}}
void init();
