"""create partner modes reward rules and referrals tables

Revision ID: 5f847cca5dcf
Revises: e303b9667566
Create Date: 2026-06-30 16:50:50.709600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f847cca5dcf'
down_revision: Union[str, Sequence[str], None] = 'e303b9667566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_modes_id'), 'partner_modes', ['id'], unique=False)
    op.create_index(op.f('ix_partner_modes_slug'), 'partner_modes', ['slug'], unique=True)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('child_user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_child_user_id'), 'referrals', ['child_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_parent_user_id'), 'referrals', ['parent_user_id'], unique=False)
    op.create_table('reward_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('partner_mode_id', sa.Integer(), nullable=False),
    sa.Column('level_1_points', sa.Integer(), nullable=False),
    sa.Column('level_2_points', sa.Integer(), nullable=False),
    sa.Column('level_3_points', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_mode_id'], ['partner_modes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_rules_id'), 'reward_rules', ['id'], unique=False)
    op.create_index(op.f('ix_reward_rules_partner_mode_id'), 'reward_rules', ['partner_mode_id'], unique=False)
    op.create_index(op.f('ix_reward_rules_service_id'), 'reward_rules', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_rules_service_id'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_partner_mode_id'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_id'), table_name='reward_rules')
    op.drop_table('reward_rules')
    op.drop_index(op.f('ix_referrals_parent_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_child_user_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_partner_modes_slug'), table_name='partner_modes')
    op.drop_index(op.f('ix_partner_modes_id'), table_name='partner_modes')
    op.drop_table('partner_modes')
    # ### end Alembic commands ###
