"""create points ledger table

Revision ID: 68199cc0dc40
Revises: 5f847cca5dcf
Create Date: 2026-06-30 16:53:56.720359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68199cc0dc40'
down_revision: Union[str, Sequence[str], None] = '5f847cca5dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('referral_level', sa.Integer(), nullable=True),
    sa.Column('reward_rule_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['reward_rule_id'], ['reward_rules.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_ledger_id'), 'points_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_points_ledger_order_id'), 'points_ledger', ['order_id'], unique=False)
    op.create_index(op.f('ix_points_ledger_service_id'), 'points_ledger', ['service_id'], unique=False)
    op.create_index(op.f('ix_points_ledger_user_id'), 'points_ledger', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_ledger_user_id'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_service_id'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_order_id'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_id'), table_name='points_ledger')
    op.drop_table('points_ledger')
    # ### end Alembic commands ###
