import bali from '../../../react-app/public/assets/heroes/bali-country-hero-approved.jpg';
import thailand from '../../../react-app/public/assets/heroes/thailand-country-hero-approved.jpg';
import russia from '../../../react-app/public/assets/heroes/russia-country-hero-approved.jpg';
import nepal from '../../../react-app/public/assets/heroes/nepal-country-hero-approved.jpg';
import uae from '../assets/worlds/uae-burj-khalifa.png';
import type {ImageMetadata} from 'astro';
import vietnam from '../assets/worlds/vietnam-hoi-an-day-ai-v1.png';
import vietnamNight from '../assets/worlds/vietnam-hoi-an-night-ai-v1.png';
import baliNight from '../../../react-app/public/assets/heroes/bali-hero-night-ai-v1-1536.webp';
import thailandNight from '../../../react-app/public/assets/heroes/thailand-hero-night-ai-v1-1536.webp';
import uaeNight from '../../../react-app/public/assets/heroes/uae-hero-night-ai-v1-1536.webp';
import nepalNight from '../../../react-app/public/assets/heroes/nepal-hero-night-ai-v1-1536.webp';
import russiaNight from '../../../react-app/public/assets/heroes/russia-hero-night-ai-v1-1536.webp';
export const worldImages: Record<string,ImageMetadata> = {bali,thailand,russia,nepal,uae,vietnam};
export const worldNightImages: Record<string,ImageMetadata> = {bali:baliNight,thailand:thailandNight,uae:uaeNight,nepal:nepalNight,russia:russiaNight,vietnam:vietnamNight};
export const worldRoute = (id:string, locale:string) => `${locale === 'en' ? '/en' : ''}${id === 'uae' ? '/uae/' : `/${id}/`}`;
