import {useState} from 'react';
import {AppIcon} from './AppIcon';
import {useI18n} from '../i18n/runtime';
import type {RouteContext} from '../api/types';
export function VisaPlanner({children,onManager,onRequests}:{children:React.ReactNode;onManager:(context:RouteContext)=>void;onRequests:()=>void}){
 const {locale}=useI18n(),en=locale==='en';const [tab,setTab]=useState('plan');
 const key='safr:app-visa-preferences:v1';const [preferences,setPreferences]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');return {purpose:Number.isInteger(saved?.purpose)&&saved.purpose>=0&&saved.purpose<4?saved.purpose:0,duration:Number.isInteger(saved?.duration)&&saved.duration>=0&&saved.duration<4?saved.duration:0};}catch{return {purpose:0,duration:0};}});
 const purposes=en?['Holiday','Business','Remote work','Not sure yet']:['Отдых','Бизнес','Удалённая работа','Пока не знаю'];
 const durations=en?['Not sure yet','Up to 1 month','1–2 months','Over 2 months']:['Пока не знаю','До 1 месяца','1–2 месяца','Больше 2 месяцев'];
 const update=(name:string,value:number)=>{const next={...preferences,[name]:value};setPreferences(next);try{sessionStorage.setItem(key,JSON.stringify(next));}catch{}};
 return <div className="visa-workspace"><header className="service-workspace-header"><span className="service-card-icon app-tone-blue"><AppIcon name="▣"/></span><div><small>{en?'BALI · YOUR SERVICES':'БАЛИ · ВАШИ СЕРВИСЫ'}</small><h1>{en?'Visas':'Визы'}</h1><p>{en?'Start with your trip. We’ll help with the next steps.':'Начните с вашей поездки. С остальным поможем.'}</p></div></header><nav className="workspace-tabs" aria-label={en?'Visa sections':'Разделы виз'}>{['plan','catalog','status'].map((id,i)=><button key={id} type="button" aria-pressed={tab===id} onClick={()=>setTab(id)}>{(en?['Find a visa','All options','My requests']:['Подобрать визу','Все варианты','Мои заявки'])[i]}</button>)}</nav>
 {tab==='plan'&&<div className="visa-plan"><form className="trip-form" onSubmit={e=>{e.preventDefault();onManager({country:'Бали',section:'Визы',service:`${purposes[preferences.purpose]}; ${durations[preferences.duration]}`});}}><small>{en?'YOUR TRIP':'ВАША ПОЕЗДКА'}</small><h2>{en?'What brings you to Bali?':'Зачем вы едете на Бали?'}</h2><fieldset><legend className="visually-hidden">{en?'Purpose':'Цель поездки'}</legend><div className="purpose-grid">{purposes.map((label,i)=><label className="purpose-choice" key={i}><input type="radio" name="purpose" checked={preferences.purpose===i} onChange={()=>update('purpose',i)}/><AppIcon name={['sun','briefcase','laptop','◎'][i]}/><span>{label}</span><span className="choice-check">✓</span></label>)}</div></fieldset><fieldset><legend>{en?'How long?':'На какой срок?'}</legend><div className="duration-options">{durations.map((label,i)=><label className="duration-choice" key={i}><input type="radio" name="duration" checked={preferences.duration===i} onChange={()=>update('duration',i)}/><span>{label}</span></label>)}</div></fieldset><p>{en?'Your assistant will clarify options and requirements for your trip.':'Ассистент уточнит подходящие варианты и требования для вашей ситуации.'}</p><button className="button primary" type="submit">{en?'Find a visa':'Подобрать визу'} <AppIcon name="→"/></button></form><aside className="trip-process"><small>{en?'WE’RE WITH YOU':'МЫ РЯДОМ'}</small><h2>{en?'A clear next step.':'Понятно, что дальше.'}</h2><ol>{(en?['Tell us about your trip','Clarify the options','Agree on the next steps']:['Расскажите о поездке','Уточним варианты','Согласуем следующие шаги']).map((x,i)=><li key={x}><span>{i+1}</span><div><strong>{x}</strong><p>{(en?['Your plans and timing.','Documents, terms and cost.','Move forward with your assistant.']:['Ваши планы и сроки.','Документы, условия и стоимость.','Продолжите вместе с ассистентом.'])[i]}</p></div></li>)}</ol></aside></div>}
 {tab==='catalog'&&children}{tab==='status'&&<div className="content-card"><h2>{en?'Your visa requests':'Ваши визовые заявки'}</h2><button className="button primary" onClick={onRequests}>{en?'Open my visas':'Открыть мои визы'}</button></div>}</div>;
}
